project: infra
source:
  repoURL: 'https://istio-release.storage.googleapis.com/charts'
  targetRevision: 1.13.5
  chart: istiod
destination:
  server: 'https://kubernetes.default.svc'
  namespace: istio-system
syncPolicy:
  automated: {}
