project: infra
source:
  repoURL: 'https://prometheus-community.github.io/helm-charts'
  targetRevision: 36.2.1
  chart: kube-prometheus-stack
destination:
  server: 'https://kubernetes.default.svc'
  namespace: monitoring
syncPolicy:
  automated: {}
